name: Go CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Run tests
      run: |
        go test -v ./...

    - name: Build
      run: |
        go build -o app .

    - name: Build Docker image
      run: |
        docker build -t helm-template-golangapp .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: helm-template-golangapp:${{ github.sha }}
