name: Go CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: actions/setup-docker@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19.5

    - name: Get dependencies
      run: |
        cd ./app/src/
        go install

    - name: Build
      run: |
        cd ./app/src/
        go build -o app .

    - name: Build Docker image
      run: |
        docker build -t helm-template-golangapp .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: helm-template-golangapp:${{ github.sha }}
