name: Go CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.x

    - name: Get dependencies
      run: |
        go get -u github.com/gin-gonic/gin@latest
        go get -u github.com/spf13/viper@latest

    - name: Build
      run: |
        go build -o app .

    - name: Build Docker image
      run: |
        docker build -t helm-template-golangapp .

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        tags: helm-template-golangapp:${{ github.sha }}
